# Generated by Django 4.2.2 on 2023-06-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cuisine_alter_recipe_options_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='name',
            new_name='type',
        ),
    ]
