# Generated by Django 4.2.2 on 2023-06-16 09:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='picture'),
        ),
    ]
