# Generated by Django 4.2.2 on 2023-06-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
